GET http://localhost:3000/inventories

###

GET http://localhost:3000/inventories/60132ef1d9b50771a73d3a52

###

POST http://localhost:3000/inventories
Content-Type: application/json

{
    "name": "Jake Cauliflower",
    "amount": 10
}

###

DELETE http://localhost:3000/inventories/60132ef1d9b50771a73d3a51

###

PATCH http://localhost:3000/inventories/60132ef1d9b50771a73d3a52
Content-Type: application/json

{
    "name": "Aspargus"
}

###
GET http://localhost:3000/pantries

###

POST http://localhost:3000/pantries
Content-Type: application/json

{
    "name": "New Pantry",
    "address": "12345 Adress Lane", 
    "inventory": [
        { "name": "Broccoli", "amount": 10 }, 
        {"name": "Apple", "amount": 10}
        ]
}

###

DELETE http://localhost:3000/pantries/60137240e0a234b18679dc14
